from pydantic import BaseModel, Field, ConfigDict
from typing import List, Optional, Dict, Any, Literal
from enum import Enum

class GoalPriority(str, Enum):
    CRITICAL = "critical"
    HIGH = "high"
    NORMAL = "normal"

class StepStatus(str, Enum):
    PENDING = "pending"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    PARTIAL_SUCCESS = "partial_success"
    COMPENSATING = "compensating"
    ROLLED_BACK = "rolled_back"

class PlanStep(BaseModel):
    """Represents a single actionable task item in a larger orchestrated sequence."""
    model_config = ConfigDict(extra="forbid")
    
    step_id: str = Field(description="Distinct identifier, e.g. 'step-1'.")
    description: str = Field(description="Natural language explanation of this task step.")
    assigned_tool: str = Field(description="The name of the tool proposed for this action. Use empty string if no specific tool needed.")
    dependencies: List[str] = Field(description="List of step_ids that must complete first. Use empty list if none.")
    requires_hitl: bool = Field(description="Whether this step mandates explicit user confirmation.")
    
    # P5: Structured Goal Details
    priority: Literal["critical", "high", "normal"] = Field(description="Task critical scale: critical, high, or normal.")
    
    # P4: Failure Semantics & Resilience Details
    status: Literal["pending", "running", "completed", "failed", "partial_success", "compensating", "rolled_back"] = Field(description="Detailed runtime execution state. Use 'pending' for new steps.")
    retry_count: int = Field(description="Number of execution retries attempted. Use 0 for new steps.")
    max_retries: int = Field(description="Strict retry policy limit. Use 2 as default.")
    compensating_action: str = Field(
        description="Explicit compensating/rollback routine if this step fails irrecoverably. Use empty string if none."
    )
    
    output: str = Field(description="Execution payload from tool result as JSON string. Use empty string if not yet executed.")
    error_trace: str = Field(description="Captured trace during step failure execution. Use empty string if no error.")

class ExecutionPlan(BaseModel):
    """Fully decomposed sequence of instructions generated by the AI Planner."""
    model_config = ConfigDict(extra="forbid")
    
    goal_id: str = Field(description="Traceable high-level goal tracking identifier. Use empty string if not assigned.")
    goal: str = Field(description="The ultimate high-level objective stated by the user.")
    complexity: str = Field(description="Subjective task analysis: low | medium | high")
    
    # Priority & Policy
    overall_priority: Literal["critical", "high", "normal"] = Field(description="Overall goal priority: critical, high, or normal.")
    
    steps: List[PlanStep] = Field(description="Sequenced array of granular execution steps.")
    next_step_id: str = Field(description="Points to the step currently slated for invocation. Use empty string if undecided.")
    is_complete: bool = Field(description="Flags if overall goal requirements have been fully achieved.")
    
    # Resilience Tracker
    failure_count: int = Field(description="Total failures across all steps. Use 0 for new plans.")
    rollback_active: bool = Field(description="Whether a rollback sequence is currently in progress.")
