import time
import json
from typing import Dict, Any, List
from langchain_core.messages import ToolMessage
from backend.app.graphs.state import WingmanState
from backend.app.graphs.execution.helpers import emit_telemetry
from backend.app.telemetry.schemas import TelemetryEventType
from backend.app.tools.registry import tool_registry
from backend.app.tools.base.interface import ToolExecutionContext
from backend.app.core.logging import logger

async def tool_executor_node(state: WingmanState) -> Dict[str, Any]:
    """
    Executes requested tool payloads generated by the Orchestrator node.
    Supports concurrent tool handling and produces LangChain ToolMessages.
    """
    start_time = time.perf_counter()
    node_name = "tool_executor"
    
    await emit_telemetry(
        state, 
        TelemetryEventType.NODE_STARTED, 
        node_name=node_name
    )
    
    # Fetch selected tool calls
    tool_calls = state.get("active_tool_calls", [])
    logger.info(f"[{node_name}] Executing {len(tool_calls)} requested tool actions.")
    
    results_messages = []
    
    # Loop through and process sequential executions
    for tc in tool_calls:
        tool_name = tc["name"]
        tool_args = tc["args"]
        tool_call_id = tc["id"]
        
        logger.info(f"[{node_name}] Invocating tool: '{tool_name}' [CallID={tool_call_id}]")
        
        await emit_telemetry(
            state,
            TelemetryEventType.TOOL_STARTED,
            node_name=node_name,
            tool_name=tool_name,
            emotion="excited",
            telemetry_label=f"Using {tool_name.replace('_', ' ').title()}",
            payload={"arguments": tool_args}
        )
        
        tool_run_start = time.perf_counter()
        
        try:
            # Inject context wrapper
            ctx = ToolExecutionContext(
                trace_id=state.get("trace_id", "gen-trace"),
                run_id=state.get("run_id", "gen-run"),
                user_timezone=state.get("timezone", "UTC"),
                is_background=state.get("is_background", False),
                has_hitl_clearance=state.get("has_hitl_clearance", False),
                metadata={
                    "session_id": state.get("session_id"),
                    "location": state.get("user_preferences", {}).get("location") if state.get("user_preferences") else None
                }
            )
            
            # Retrieve instance
            tool_instance = tool_registry.get_tool(tool_name)
            
            # Run standard execution contract
            result = await tool_instance.run(tool_args, ctx)
            tool_duration = (time.perf_counter() - tool_run_start) * 1000
            
            # Collect authenticity logs
            ledger_entry = {
                "tool_name": tool_name,
                "timestamp": result.timestamp.isoformat(),
                "authenticity": result.authenticity,
                "simulated": result.simulated,
                "provider_connected": result.provider_connected,
                "confidence_penalty": result.confidence_penalty
            }
            
            # Update running ledger and confidence
            state.setdefault("execution_authenticity_ledger", []).append(ledger_entry)
            current_conf = state.get("global_confidence_score", 1.0)
            state["global_confidence_score"] = max(0.0, current_conf - result.confidence_penalty)
            
            if result.success:
                logger.info(f"[{node_name}] Tool '{tool_name}' execution succeeded [Auth={result.authenticity}].")
                
                # Construct conversational history output, explicitly attaching execution metadata for prompt transparency
                enriched_output = {
                    "data": result.output,
                    "_authenticity_meta": {
                        "authenticity": result.authenticity,
                        "simulated": result.simulated,
                        "provider_connected": result.provider_connected
                    }
                }
                
                results_messages.append(ToolMessage(
                    content=json.dumps(enriched_output),
                    tool_call_id=tool_call_id,
                    name=tool_name
                ))
                
                await emit_telemetry(
                    state,
                    TelemetryEventType.TOOL_COMPLETED,
                    node_name=node_name,
                    tool_name=tool_name,
                    payload={
                        "output_preview": str(result.output)[:200],
                        "authenticity": result.authenticity
                    },
                    duration_ms=tool_duration
                )

            else:
                # Tool reported controlled execution error
                logger.warning(f"[{node_name}] Tool '{tool_name}' reported execution error: {result.error}")
                results_messages.append(ToolMessage(
                    content=f"Error during execution: {result.error}",
                    tool_call_id=tool_call_id,
                    name=tool_name,
                    status="error"
                ))
                
                await emit_telemetry(
                    state,
                    TelemetryEventType.TOOL_FAILED,
                    node_name=node_name,
                    tool_name=tool_name,
                    payload={"error": result.error},
                    duration_ms=tool_duration
                )
                
        except Exception as e:
            # System collapsed during tool processing
            tool_duration = (time.perf_counter() - tool_run_start) * 1000
            logger.error(f"[{node_name}] Total collapse executing {tool_name}: {e}", exc_info=True)
            
            results_messages.append(ToolMessage(
                content=f"System Error invoking tool: {str(e)}",
                tool_call_id=tool_call_id,
                name=tool_name,
                status="error"
            ))
            
            await emit_telemetry(
                state,
                TelemetryEventType.TOOL_FAILED,
                node_name=node_name,
                tool_name=tool_name,
                payload={"error": str(e)},
                duration_ms=tool_duration
            )

    # 3. Post-Execution Plan State Advancement & Resilience Policies
    updated_plan = state.get("execution_plan")
    if updated_plan and "steps" in updated_plan:
        from backend.app.resilience.manager import ExecutionResilienceManager
        
        current_step_id = updated_plan.get("next_step_id")
        has_failures = any(isinstance(msg, ToolMessage) and msg.status == "error" for msg in results_messages)
        
        last_out = {}
        if results_messages:
            try:
                last_out = json.loads(results_messages[-1].content)
            except Exception:
                last_out = {"raw": results_messages[-1].content}
        
        if has_failures:
            # Delegate execution flow control to resilience manager
            err_trace = results_messages[-1].content if results_messages else "Unknown runtime error"
            updated_plan, should_retry = ExecutionResilienceManager.handle_step_failure(
                plan=updated_plan,
                step_id=current_step_id,
                error_msg=err_trace
            )
            logger.warning(
                f"[{node_name}] Step failure handled. Next: {updated_plan.get('next_step_id')} | "
                f"Retry Scheduled: {should_retry}"
            )
        else:
            # Standard forward advancement
            updated_plan = ExecutionResilienceManager.record_step_success(
                plan=updated_plan,
                step_id=current_step_id,
                output=last_out
            )
            logger.info(
                f"[{node_name}] Step completed successfully. Next: {updated_plan.get('next_step_id')}"
            )

    total_duration = (time.perf_counter() - start_time) * 1000
    
    await emit_telemetry(
        state,
        TelemetryEventType.NODE_COMPLETED,
        node_name=node_name,
        duration_ms=total_duration
    )
    
    # Wipe the active_tool_calls list since they're now executed, commit Plan updates
    return_state = {
        "messages": results_messages,
        "active_node": node_name,
        "active_tool_calls": [],
        "execution_authenticity_ledger": state.get("execution_authenticity_ledger", []),
        "global_confidence_score": state.get("global_confidence_score", 1.0)
    }
    
    if updated_plan:

        return_state["execution_plan"] = updated_plan
        
    return return_state
