from pydantic import BaseModel, Field
from typing import List, Optional, Dict, Any
from datetime import datetime

class ChatMessage(BaseModel):
    role: str = Field(..., description="Role of message creator (user, assistant, system)")
    content: str = Field(..., description="Text payload of message")
    timestamp: Optional[datetime] = Field(default_factory=datetime.now)

class ChatRequest(BaseModel):
    message: str = Field(..., description="The latest message from the user")
    history: List[ChatMessage] = Field(default=[], description="Prior chat message history")
    priority_tier: str = Field(default="MEDIUM", description="Execution priority: CRITICAL, HIGH, MEDIUM, LOW, BACKGROUND")
    metadata: Dict[str, Any] = Field(default={}, description="Client injected context (timezone, timestamp)")

class ChatResponse(BaseModel):
    response: str = Field(..., description="Text response generated by assistant")
    session_id: Optional[str] = Field(None, description="Active session reference")
    timestamp: datetime = Field(default_factory=datetime.now)

class ChatHistoryResponse(BaseModel):
    role: str = Field(..., description="The speaker's role: user or assistant.")
    content: str = Field(..., description="The text payload content.")
    session_id: str = Field(..., description="Parent interaction session thread.")
    created_at: datetime = Field(..., description="Creation timestamp.")
    trace_id: Optional[str] = Field(None, description="Associated execution trace chain.")
